create table course (
    id bigint generated by default as identity,
    title varchar(255) not null,
    creator_id bigint not null,
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id)
);

create table ns_user (
    id bigint generated by default as identity,
    user_id varchar(20) not null,
    password varchar(20) not null,
    name varchar(20) not null,
    email varchar(50),
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id)
);

create table question (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    contents clob,
    deleted boolean not null,
    title varchar(100) not null,
    writer_id bigint,
    primary key (id)
);

create table answer (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    contents clob,
    deleted boolean not null,
    question_id bigint,
    writer_id bigint,
    primary key (id)
);

create table delete_history (
    id bigint not null,
    content_id bigint,
    content_type varchar(255),
    created_date timestamp,
    deleted_by_id bigint,
    primary key (id)
);

create table session_image (
    id bigint not null,
    image_size integer,
    type varchar(50) not null,
    width integer,
    height integer,
    primary key (id)
);

create table session (
    id bigint not null,
    session_image_id bigint,
    session_state varchar(50) not null,
    price bigint default 0,
    max_capacity integer,
    start_date timestamp not null,
    end_date timestamp not null,
    primary key (id),
    FOREIGN KEY (session_image_id) REFERENCES session_image(id)
);

create table enrollment (
    session_id bigint not null,
    ns_user_id bigint not null,
    PRIMARY KEY (session_id, ns_user_id),
    FOREIGN KEY (session_id) REFERENCES session(id),
    FOREIGN KEY (ns_user_id) REFERENCES ns_user(id)
);
